version: '3.8'

services:
  spring-boot:
    image: app:latest
    container_name: employee-app
    working_dir: /employeeapp
    volumes:
      - ./target/EmployeePage-0.0.1-SNAPSHOT.jar:/employeeapp/app.jar
    ports:
      - "8080:8080"
    environment:
       SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/aplikacija
       SPRING_DATASOURCE_USERNAME: app
       SPRING_DATASOURCE_PASSWORD: 12345
       SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - db
    networks:
      - my-network
  db:
    image: postgre:latest
    container_name: postgredb
    ports:
      - "5433:5432"
    environment:
       POSTGRES_DB: aplikacija
       POSTGRES_USER: app
       POSTGRES_PASSWORD: 12345
    networks:
      - my-network
networks:
  my-network:
    driver: bridge
